version: '3.1'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678" # debugpy
    depends_on:
      - db
    env_file:
      - .env
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
      - /app/venv
    command: flask run --host=0.0.0.0 --port=5000

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-data:/docker-entrypoint-initdb.d/

volumes:
  postgres-data:
