services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
      - "5678:5678" # debugpy
    depends_on:
      - db
    env_file:
      - .env # Necessary?
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
      - /app/venv
    command: flask run --host=0.0.0.0 --port=5000

  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: correctomatic
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-data:/docker-entrypoint-initdb.d/

volumes:
  postgres-data:
